# ----------------------------------------
# Created on: Tue Nov 18 18:47:52 2025
# Auto generated by Pango
# ----------------------------------------

vlib  work
vmap  work ./work
vmap  usim "E:/User/Files/project_self/OPHW_25H/workspace/16work/project/pango_sim_libraries/usim"
vmap  adc_e2 "E:/User/Files/project_self/OPHW_25H/workspace/16work/project/pango_sim_libraries/adc_e2"
vmap  ddc_e2 "E:/User/Files/project_self/OPHW_25H/workspace/16work/project/pango_sim_libraries/ddc_e2"
vmap  dll_e2 "E:/User/Files/project_self/OPHW_25H/workspace/16work/project/pango_sim_libraries/dll_e2"
vmap  hsstlp_lane "E:/User/Files/project_self/OPHW_25H/workspace/16work/project/pango_sim_libraries/hsstlp_lane"
vmap  hsstlp_pll "E:/User/Files/project_self/OPHW_25H/workspace/16work/project/pango_sim_libraries/hsstlp_pll"
vmap  iolhr_dft "E:/User/Files/project_self/OPHW_25H/workspace/16work/project/pango_sim_libraries/iolhr_dft"
vmap  ipal_e1 "E:/User/Files/project_self/OPHW_25H/workspace/16work/project/pango_sim_libraries/ipal_e1"
vmap  ipal_e2 "E:/User/Files/project_self/OPHW_25H/workspace/16work/project/pango_sim_libraries/ipal_e2"
vmap  iserdes_e2 "E:/User/Files/project_self/OPHW_25H/workspace/16work/project/pango_sim_libraries/iserdes_e2"
vmap  oserdes_e2 "E:/User/Files/project_self/OPHW_25H/workspace/16work/project/pango_sim_libraries/oserdes_e2"
vmap  pciegen2 "E:/User/Files/project_self/OPHW_25H/workspace/16work/project/pango_sim_libraries/pciegen2"
vlog -work work   \
"E:/User/Files/project_self/OPHW_25H/workspace/16work/design/asyn_rst_syn.v" \
"E:/User/Files/project_self/OPHW_25H/workspace/16work/design/dvi_encoder.v" \
"E:/User/Files/project_self/OPHW_25H/workspace/16work/design/dvi_transmitter_top.v" \
"E:/User/Files/project_self/OPHW_25H/workspace/16work/design/hdmi_picture_grey.v" \
"E:/User/Files/project_self/OPHW_25H/workspace/16work/design/RGB2YCbCr.v" \
"E:/User/Files/project_self/OPHW_25H/workspace/16work/design/serializer_10_to_1.v" \
"E:/User/Files/project_self/OPHW_25H/workspace/16work/design/sync_vg.v" \
"E:/User/Files/project_self/OPHW_25H/workspace/16work/design/video_display.v" \
"E:/User/Files/project_self/OPHW_25H/workspace/16work/design/area_bin.v" \
"E:/User/Files/project_self/OPHW_25H/workspace/16work/design/binarization.v" \
"E:/User/Files/project_self/OPHW_25H/workspace/16work/design/data_delay.v" \
"E:/User/Files/project_self/OPHW_25H/workspace/16work/design/signal_delay.v" \
"E:/User/Files/project_self/OPHW_25H/workspace/16work/design/matrix_3x3.v" \
"E:/User/Files/project_self/OPHW_25H/workspace/16work/project/ipcore/pll_0/pll_0.v" \
"E:/User/Files/project_self/OPHW_25H/workspace/16work/project/ipcore/pll_1/pll_1.v" \
"E:/User/Files/project_self/OPHW_25H/workspace/16work/project/ipcore/blk_mem_gen_0/rtl/ipm2l_rom_v1_8_blk_mem_gen_0.v" \
"E:/User/Files/project_self/OPHW_25H/workspace/16work/project/ipcore/blk_mem_gen_0/rtl/ipm2l_spram_v1_8_blk_mem_gen_0.v" \
"E:/User/Files/project_self/OPHW_25H/workspace/16work/project/ipcore/blk_mem_gen_0/blk_mem_gen_0.v" \
"E:/User/Files/project_self/OPHW_25H/workspace/16work/project/ipcore/fifo_line_buf/rtl/ipm2l_fifo_ctrl_v1_1_fifo_line_buf.v" \
"E:/User/Files/project_self/OPHW_25H/workspace/16work/project/ipcore/fifo_line_buf/rtl/ipm2l_sdpram_v1_10_fifo_line_buf.v" \
"E:/User/Files/project_self/OPHW_25H/workspace/16work/project/ipcore/fifo_line_buf/rtl/ipm2l_fifo_v1_10_fifo_line_buf.v" \
"E:/User/Files/project_self/OPHW_25H/workspace/16work/project/ipcore/fifo_line_buf/fifo_line_buf.v" \
"E:/User/Files/project_self/OPHW_25H/workspace/16work/simulation/matrix_3x3.v" \
"E:/User/Files/project_self/OPHW_25H/workspace/16work/simulation/matrix_tb.v" \
"E:/User/Files/project_self/OPHW_25H/workspace/16work/simulation/area_bin.v" \
"E:/User/Files/project_self/OPHW_25H/workspace/16work/simulation/asyn_rst_syn.v" \
"E:/User/Files/project_self/OPHW_25H/workspace/16work/simulation/binarization.v" \
"E:/User/Files/project_self/OPHW_25H/workspace/16work/simulation/data_delay.v" \
"E:/User/Files/project_self/OPHW_25H/workspace/16work/simulation/dvi_encoder.v" \
"E:/User/Files/project_self/OPHW_25H/workspace/16work/simulation/dvi_transmitter_top.v" \
"E:/User/Files/project_self/OPHW_25H/workspace/16work/simulation/hdmi_picture_grey.v" \
"E:/User/Files/project_self/OPHW_25H/workspace/16work/simulation/RGB2YCbCr.v" \
"E:/User/Files/project_self/OPHW_25H/workspace/16work/simulation/serializer_10_to_1.v" \
"E:/User/Files/project_self/OPHW_25H/workspace/16work/simulation/signal_delay.v" \
"E:/User/Files/project_self/OPHW_25H/workspace/16work/simulation/sync_vg.v" \
"E:/User/Files/project_self/OPHW_25H/workspace/16work/simulation/video_display.v" \
"E:/User/Files/project_self/OPHW_25H/workspace/16work/simulation/top_tb.v" 

# ----------------------------------------
