#Generated by Fabric Compiler ( version 2022.2-SP6.4 <build 146967> ) at Sun Nov 16 18:09:28 2025

add_design E:/User/Files/project_self/OPHW_25H/OPHW_25H_TEST/1_Demo/Basic/06_fifo_test/project/ipcore/fifo_test/fifo_test.idf
