#Generated by Fabric Compiler ( version 2022.2-SP6.4 <build 146967> ) at Sat Nov 15 15:11:10 2025

remove_design -verilog "E:/User/Files/project_self/OPHW_25H/OPHW_25H_TEST/1_Demo/Advanced/12_HDMI_picture_display/design/hdmi_test.v"
add_design "E:/User/Files/project_self/OPHW_25H/OPHW_25H_TEST/1_Demo/Advanced/12_HDMI_picture_display/design/hdmi_picture_display.v"
set_arch -family Logos2 -device PG2L25H -speedgrade -6 -package MBG325
compile -top_module hdmi_picture_display
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos2 -device PG2L25H -speedgrade -6 -package MBG325
compile -top_module hdmi_picture_display
set_arch -family Logos2 -device PG2L25H -speedgrade -6 -package MBG325
compile -top_module hdmi_picture_display
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos2 -device PG2L25H -speedgrade -6 -package MBG325
compile -top_module hdmi_picture_display
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos2 -device PG2L25H -speedgrade -6 -package MBG325
compile -top_module hdmi_picture_display
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
