# ----------------------------------------
# Created on: Tue Nov 25 13:01:51 2025
# Auto generated by Pango
# ----------------------------------------

vlib  work
vmap  work ./work
vmap  usim "E:/User/Files/project_self/OPHW_25H/OPHW_25H_TEST/1_Demo/Basic/06_fifo_test/project/pango_sim_libraries/usim"
vmap  adc_e2 "E:/User/Files/project_self/OPHW_25H/OPHW_25H_TEST/1_Demo/Basic/06_fifo_test/project/pango_sim_libraries/adc_e2"
vmap  ddc_e2 "E:/User/Files/project_self/OPHW_25H/OPHW_25H_TEST/1_Demo/Basic/06_fifo_test/project/pango_sim_libraries/ddc_e2"
vmap  dll_e2 "E:/User/Files/project_self/OPHW_25H/OPHW_25H_TEST/1_Demo/Basic/06_fifo_test/project/pango_sim_libraries/dll_e2"
vmap  hsstlp_lane "E:/User/Files/project_self/OPHW_25H/OPHW_25H_TEST/1_Demo/Basic/06_fifo_test/project/pango_sim_libraries/hsstlp_lane"
vmap  hsstlp_pll "E:/User/Files/project_self/OPHW_25H/OPHW_25H_TEST/1_Demo/Basic/06_fifo_test/project/pango_sim_libraries/hsstlp_pll"
vmap  iolhr_dft "E:/User/Files/project_self/OPHW_25H/OPHW_25H_TEST/1_Demo/Basic/06_fifo_test/project/pango_sim_libraries/iolhr_dft"
vmap  ipal_e1 "E:/User/Files/project_self/OPHW_25H/OPHW_25H_TEST/1_Demo/Basic/06_fifo_test/project/pango_sim_libraries/ipal_e1"
vmap  ipal_e2 "E:/User/Files/project_self/OPHW_25H/OPHW_25H_TEST/1_Demo/Basic/06_fifo_test/project/pango_sim_libraries/ipal_e2"
vmap  iserdes_e2 "E:/User/Files/project_self/OPHW_25H/OPHW_25H_TEST/1_Demo/Basic/06_fifo_test/project/pango_sim_libraries/iserdes_e2"
vmap  oserdes_e2 "E:/User/Files/project_self/OPHW_25H/OPHW_25H_TEST/1_Demo/Basic/06_fifo_test/project/pango_sim_libraries/oserdes_e2"
vmap  pciegen2 "E:/User/Files/project_self/OPHW_25H/OPHW_25H_TEST/1_Demo/Basic/06_fifo_test/project/pango_sim_libraries/pciegen2"
vlog -work work   \
"E:/User/Files/project_self/OPHW_25H/OPHW_25H_TEST/1_Demo/Basic/06_fifo_test/design/fifo_test_top.v" \
"E:/User/Files/project_self/OPHW_25H/OPHW_25H_TEST/1_Demo/Basic/06_fifo_test/project/ipcore/fifo_test/rtl/ipm2l_fifo_ctrl_v1_1_fifo_test.v" \
"E:/User/Files/project_self/OPHW_25H/OPHW_25H_TEST/1_Demo/Basic/06_fifo_test/project/ipcore/fifo_test/rtl/ipm2l_sdpram_v1_10_fifo_test.v" \
"E:/User/Files/project_self/OPHW_25H/OPHW_25H_TEST/1_Demo/Basic/06_fifo_test/project/ipcore/fifo_test/rtl/ipm2l_fifo_v1_10_fifo_test.v" \
"E:/User/Files/project_self/OPHW_25H/OPHW_25H_TEST/1_Demo/Basic/06_fifo_test/project/ipcore/fifo_test/fifo_test.v" \
"E:/User/Files/project_self/OPHW_25H/OPHW_25H_TEST/1_Demo/Basic/06_fifo_test/simulation/fifo_test_tb.v" \
"E:/User/Files/project_self/OPHW_25H/OPHW_25H_TEST/1_Demo/Basic/06_fifo_test/simulation/fifo_test_top.v" 

# ----------------------------------------
