#Generated by Fabric Compiler ( version 2022.2-SP6.4 <build 146967> ) at Mon Nov 17 00:59:02 2025

set_arch -family Logos2 -device PG2L25H -speedgrade -6 -package MBG325
compile -top_module matrix_3x3
