#Generated by Fabric Compiler ( version 2022.2-SP6.4 <build 146967> ) at Fri Nov 21 08:59:22 2025

set_arch -family Logos2 -device PG2L25H -speedgrade -6 -package MBG325
compile -top_module key_led_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos2 -device PG2L25H -speedgrade -6 -package MBG325
compile -top_module key_led_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
