# ----------------------------------------
# Created on: Fri Nov 14 11:03:37 2025
# Auto generated by Pango
# ----------------------------------------

vlib  work
vmap  work ./work
vmap  usim "E:/User/Files/project_self/OPHW_25H/workspace/01_led_test/project/pango_sim_libraries/usim"
vmap  adc_e2 "E:/User/Files/project_self/OPHW_25H/workspace/01_led_test/project/pango_sim_libraries/adc_e2"
vmap  ddc_e2 "E:/User/Files/project_self/OPHW_25H/workspace/01_led_test/project/pango_sim_libraries/ddc_e2"
vmap  dll_e2 "E:/User/Files/project_self/OPHW_25H/workspace/01_led_test/project/pango_sim_libraries/dll_e2"
vmap  hsstlp_lane "E:/User/Files/project_self/OPHW_25H/workspace/01_led_test/project/pango_sim_libraries/hsstlp_lane"
vmap  hsstlp_pll "E:/User/Files/project_self/OPHW_25H/workspace/01_led_test/project/pango_sim_libraries/hsstlp_pll"
vmap  iolhr_dft "E:/User/Files/project_self/OPHW_25H/workspace/01_led_test/project/pango_sim_libraries/iolhr_dft"
vmap  ipal_e1 "E:/User/Files/project_self/OPHW_25H/workspace/01_led_test/project/pango_sim_libraries/ipal_e1"
vmap  ipal_e2 "E:/User/Files/project_self/OPHW_25H/workspace/01_led_test/project/pango_sim_libraries/ipal_e2"
vmap  iserdes_e2 "E:/User/Files/project_self/OPHW_25H/workspace/01_led_test/project/pango_sim_libraries/iserdes_e2"
vmap  oserdes_e2 "E:/User/Files/project_self/OPHW_25H/workspace/01_led_test/project/pango_sim_libraries/oserdes_e2"
vmap  pciegen2 "E:/User/Files/project_self/OPHW_25H/workspace/01_led_test/project/pango_sim_libraries/pciegen2"
vlog -work work   \
"E:/User/Files/project_self/OPHW_25H/workspace/01_led_test/design/01_led_test.v" \
"E:/User/Files/project_self/OPHW_25H/workspace/01_led_test/simulation/01_led_test.v" \
"E:/User/Files/project_self/OPHW_25H/workspace/01_led_test/simulation/tb_led_test.v" 

# ----------------------------------------
