# ----------------------------------------
# Created on: Tue Nov 25 13:05:06 2025
# Auto generated by Pango
# ----------------------------------------

vlib  work
vmap  work ./work
vmap  usim "E:/User/Files/project_self/OPHW_25H/OPHW_25H_TEST/1_Demo/Advanced/15_matrix_3x3/project/pango_sim_libraries/usim"
vmap  adc_e2 "E:/User/Files/project_self/OPHW_25H/OPHW_25H_TEST/1_Demo/Advanced/15_matrix_3x3/project/pango_sim_libraries/adc_e2"
vmap  ddc_e2 "E:/User/Files/project_self/OPHW_25H/OPHW_25H_TEST/1_Demo/Advanced/15_matrix_3x3/project/pango_sim_libraries/ddc_e2"
vmap  dll_e2 "E:/User/Files/project_self/OPHW_25H/OPHW_25H_TEST/1_Demo/Advanced/15_matrix_3x3/project/pango_sim_libraries/dll_e2"
vmap  hsstlp_lane "E:/User/Files/project_self/OPHW_25H/OPHW_25H_TEST/1_Demo/Advanced/15_matrix_3x3/project/pango_sim_libraries/hsstlp_lane"
vmap  hsstlp_pll "E:/User/Files/project_self/OPHW_25H/OPHW_25H_TEST/1_Demo/Advanced/15_matrix_3x3/project/pango_sim_libraries/hsstlp_pll"
vmap  iolhr_dft "E:/User/Files/project_self/OPHW_25H/OPHW_25H_TEST/1_Demo/Advanced/15_matrix_3x3/project/pango_sim_libraries/iolhr_dft"
vmap  ipal_e1 "E:/User/Files/project_self/OPHW_25H/OPHW_25H_TEST/1_Demo/Advanced/15_matrix_3x3/project/pango_sim_libraries/ipal_e1"
vmap  ipal_e2 "E:/User/Files/project_self/OPHW_25H/OPHW_25H_TEST/1_Demo/Advanced/15_matrix_3x3/project/pango_sim_libraries/ipal_e2"
vmap  iserdes_e2 "E:/User/Files/project_self/OPHW_25H/OPHW_25H_TEST/1_Demo/Advanced/15_matrix_3x3/project/pango_sim_libraries/iserdes_e2"
vmap  oserdes_e2 "E:/User/Files/project_self/OPHW_25H/OPHW_25H_TEST/1_Demo/Advanced/15_matrix_3x3/project/pango_sim_libraries/oserdes_e2"
vmap  pciegen2 "E:/User/Files/project_self/OPHW_25H/OPHW_25H_TEST/1_Demo/Advanced/15_matrix_3x3/project/pango_sim_libraries/pciegen2"
vlog -work work   \
"E:/User/Files/project_self/OPHW_25H/OPHW_25H_TEST/1_Demo/Advanced/15_matrix_3x3/design/matrix_3x3.v" \
"E:/User/Files/project_self/OPHW_25H/OPHW_25H_TEST/1_Demo/Advanced/15_matrix_3x3/project/ipcore/fifo_line_buffer/rtl/ipm2l_fifo_ctrl_v1_1_fifo_line_buffer.v" \
"E:/User/Files/project_self/OPHW_25H/OPHW_25H_TEST/1_Demo/Advanced/15_matrix_3x3/project/ipcore/fifo_line_buffer/rtl/ipm2l_sdpram_v1_10_fifo_line_buffer.v" \
"E:/User/Files/project_self/OPHW_25H/OPHW_25H_TEST/1_Demo/Advanced/15_matrix_3x3/project/ipcore/fifo_line_buffer/rtl/ipm2l_fifo_v1_10_fifo_line_buffer.v" \
"E:/User/Files/project_self/OPHW_25H/OPHW_25H_TEST/1_Demo/Advanced/15_matrix_3x3/project/ipcore/fifo_line_buffer/fifo_line_buffer.v" \
"E:/User/Files/project_self/OPHW_25H/OPHW_25H_TEST/1_Demo/Advanced/15_matrix_3x3/simulation/matrix_3x3.v" \
"E:/User/Files/project_self/OPHW_25H/OPHW_25H_TEST/1_Demo/Advanced/15_matrix_3x3/simulation/matrix_tb.v" 

# ----------------------------------------
